### ISSUE TITLE
Become compatible with Node != 6

### ISSUE THREAD

**Issue by skidding** [tkjone/pretty-logs#3]
I'm using Node 7.4 and `yarn install` no longer works due to [this](https://github.com/tkjone/pretty-logs/blob/3ce1888ea9d0604ffd7ce913e6cd97321641ff78/package.json#L25-L26).

![image](https://cloud.githubusercontent.com/assets/250750/25708662/d313714e-30ef-11e7-9bd8-deecc29bbc36.png)

**Comment by tkjone** [comment]
Resolved.
